import Head from "next/head";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { auth, db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  const [user, loading] = useAuthState(auth);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"))
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({
        ...doc.data(),
        id: doc.id
      })))
    });
    return unsubscribe;
  }

  useEffect(() => {
    getPosts();
  }, [])

  return (
    <div>
      <Head>
        <title>EverBloggery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <div className="flex justify-center">
          { !user ? "Join now to see what people are saying" : "See what other people are saying" }
        </div>
        {allPosts.map((post) => (
        <Message key={post.id} {...post}>
          <Link href={{pathname: `/${post.id}`, query: {...post}}}>
            <button>
            {post.comments?.length > 0 ? post.comments?.length : 0} comments
            </button>
          </Link>
        </Message>
        ))}
      </div>
    </div>
  )
}
